services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:0-7.0
    entrypoint:
    - sleep
    - infinity
    init: true
    user: root
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__ByteBankConnection=Server=db;User ID=sa;Password=P@ssw0rd;Initial Catalog=ByteBank;TrustServerCertificate=true;
      - ConnectionStrings__IdentityConnection=Server=db;User ID=sa;Password=P@ssw0rd;Initial Catalog=Identity;TrustServerCertificate=true;
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
